name: Set up NIP
description: Install the requirements and the nip package
runs:
  using: "composite"
  steps:
    - name: Install pipx
      run: |
        sudo apt install -y pipx && pipx ensurepath
      shell: bash
    - name: Install uv
      run: |
        pipx install uv==0.7.13
      shell: bash
    - name: Install dependencies with uv
      run: |
        uv sync
      shell: bash
