name: Set up NIP
description: Install the requirements and the nip package
runs:
  using: "composite"
  steps:
    - name: Install prerequisites
      run: |
        sudo apt update
        sudo apt install g++ python-dev-is-python3
      shell: bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements_dev.txt
      shell: bash
    - name: Install the package locally
      run: |
        pip install .
      shell: bash
