# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python tests

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Setup NIP
        uses: ./.github/actions/setup-nip@v1
      - name: Test with pytest
        run: |
          python -m pytest
      - name: Check formatting with black
        run: |
          # stop the build if there are black formatting errors
          black --check .
      - name: Check linting with ruff
        run: |
          # stop the build if there are ruff linting errors
          ruff check .
